import 'dart:ui';

import 'package:quran_app/models/categoris_model.dart';
import 'package:quran_app/models/surah_model.dart';

final kPrimaryColor = const Color.fromARGB(255, 183, 196, 155);
final List<CategoryModel> category = [
  CategoryModel(Name: 'القرآن الكريم', image: 'assets/images/quran.png'),
  CategoryModel(Name: 'مواعيد الاذان', image: 'assets/images/dome.png'),
];

List<SurahModel> surahs = [
  SurahModel("الْفَاتِحَة", surahNumber: 1, ayatNumber: 7, revelationPlace: "مكية"),
  SurahModel("البَقَرَة", surahNumber: 2, ayatNumber: 286, revelationPlace: "مدنية"),
  SurahModel("آلِ عِمْرَان", surahNumber: 3, ayatNumber: 200, revelationPlace: "مدنية"),
  SurahModel("النِّسَاء", surahNumber: 4, ayatNumber: 176, revelationPlace: "مدنية"),
  SurahModel("الْمَائِدَة", surahNumber: 5, ayatNumber: 120, revelationPlace: "مدنية"),
  SurahModel("الْأَنْعَام", surahNumber: 6, ayatNumber: 165, revelationPlace: "مكية"),
  SurahModel("الْأَعْرَاف", surahNumber: 7, ayatNumber: 206, revelationPlace: "مكية"),
  SurahModel("الْأَنْفَال", surahNumber: 8, ayatNumber: 75, revelationPlace: "مدنية"),
  SurahModel("التَّوْبَة", surahNumber: 9, ayatNumber: 129, revelationPlace: "مدنية"),
  SurahModel("يُونُس", surahNumber: 10, ayatNumber: 109, revelationPlace: "مكية"),
  SurahModel("هُود", surahNumber: 11, ayatNumber: 123, revelationPlace: "مكية"),
  SurahModel("يُوسُف", surahNumber: 12, ayatNumber: 111, revelationPlace: "مكية"),
  SurahModel("الرَّعْد", surahNumber: 13, ayatNumber: 43, revelationPlace: "مدنية"),
  SurahModel("إِبْرَاهِيم", surahNumber: 14, ayatNumber: 52, revelationPlace: "مكية"),
  SurahModel("الْحِجْر", surahNumber: 15, ayatNumber: 99, revelationPlace: "مكية"),
  SurahModel("النَّحْل", surahNumber: 16, ayatNumber: 128, revelationPlace: "مكية"),
  SurahModel("الْإِسْرَاء", surahNumber: 17, ayatNumber: 111, revelationPlace: "مكية"),
  SurahModel("الْكَهْف", surahNumber: 18, ayatNumber: 110, revelationPlace: "مكية"),
  SurahModel("مَرْيَم", surahNumber: 19, ayatNumber: 98, revelationPlace: "مكية"),
  SurahModel("طه", surahNumber: 20, ayatNumber: 135, revelationPlace: "مكية"),
  SurahModel("الْأَنْبِيَاء", surahNumber: 21, ayatNumber: 112, revelationPlace: "مكية"),
  SurahModel("الْحَجّ", surahNumber: 22, ayatNumber: 78, revelationPlace: "مدنية"),
  SurahModel("الْمُؤْمِنُونَ", surahNumber: 23, ayatNumber: 118, revelationPlace: "مكية"),
  SurahModel("النُّور", surahNumber: 24, ayatNumber: 64, revelationPlace: "مدنية"),
  SurahModel("الْفُرْقَان", surahNumber: 25, ayatNumber: 77, revelationPlace: "مكية"),
  SurahModel("الشُّعَرَاء", surahNumber: 26, ayatNumber: 227, revelationPlace: "مكية"),
  SurahModel("النَّمْل", surahNumber: 27, ayatNumber: 93, revelationPlace: "مكية"),
  SurahModel("الْقَصَص", surahNumber: 28, ayatNumber: 88, revelationPlace: "مكية"),
  SurahModel("الْعَنْكَبُوت", surahNumber: 29, ayatNumber: 69, revelationPlace: "مكية"),
  SurahModel("الرُّوم", surahNumber: 30, ayatNumber: 60, revelationPlace: "مكية"),
  SurahModel("لُقْمَان", surahNumber: 31, ayatNumber: 34, revelationPlace: "مكية"),
  SurahModel("السَّجْدَة", surahNumber: 32, ayatNumber: 30, revelationPlace: "مكية"),
  SurahModel("الْأَحْزَاب", surahNumber: 33, ayatNumber: 73, revelationPlace: "مدنية"),
  SurahModel("سَبَأ", surahNumber: 34, ayatNumber: 54, revelationPlace: "مكية"),
  SurahModel("فَاطِر", surahNumber: 35, ayatNumber: 45, revelationPlace: "مكية"),
  SurahModel("يس", surahNumber: 36, ayatNumber: 83, revelationPlace: "مكية"),
  SurahModel("الصَّافَّات", surahNumber: 37, ayatNumber: 182, revelationPlace: "مكية"),
  SurahModel("ص", surahNumber: 38, ayatNumber: 88, revelationPlace: "مكية"),
  SurahModel("الزُّمَر", surahNumber: 39, ayatNumber: 75, revelationPlace: "مكية"),
  SurahModel("غَافِر", surahNumber: 40, ayatNumber: 85, revelationPlace: "مكية"),
  SurahModel("فُصِّلَت", surahNumber: 41, ayatNumber: 54, revelationPlace: "مكية"),
  SurahModel("الشُّورَى", surahNumber: 42, ayatNumber: 53, revelationPlace: "مكية"),
  SurahModel("الزُّخْرُف", surahNumber: 43, ayatNumber: 89, revelationPlace: "مكية"),
  SurahModel("الدُّخَان", surahNumber: 44, ayatNumber: 59, revelationPlace: "مكية"),
  SurahModel("الْجَاثِيَة", surahNumber: 45, ayatNumber: 37, revelationPlace: "مكية"),
  SurahModel("الْأَحْقَاف", surahNumber: 46, ayatNumber: 35, revelationPlace: "مكية"),
  SurahModel("مُحَمَّد", surahNumber: 47, ayatNumber: 38, revelationPlace: "مدنية"),
  SurahModel("الْفَتْح", surahNumber: 48, ayatNumber: 29, revelationPlace: "مدنية"),
  SurahModel("الْحُجُرَات", surahNumber: 49, ayatNumber: 18, revelationPlace: "مدنية"),
  SurahModel("ق", surahNumber: 50, ayatNumber: 45, revelationPlace: "مكية"),
  SurahModel("الذَّارِيَات", surahNumber: 51, ayatNumber: 60, revelationPlace: "مكية"),
  SurahModel("الطُّور", surahNumber: 52, ayatNumber: 49, revelationPlace: "مكية"),
  SurahModel("النَّجْم", surahNumber: 53, ayatNumber: 62, revelationPlace: "مكية"),
  SurahModel("الْقَمَر", surahNumber: 54, ayatNumber: 55, revelationPlace: "مكية"),
  SurahModel("الرَّحْمَن", surahNumber: 55, ayatNumber: 78, revelationPlace: "مدنية"),
  SurahModel("الْوَاقِعَة", surahNumber: 56, ayatNumber: 96, revelationPlace: "مكية"),
  SurahModel("الْحَدِيد", surahNumber: 57, ayatNumber: 29, revelationPlace: "مدنية"),
  SurahModel("الْمُجَادِلَة", surahNumber: 58, ayatNumber: 22, revelationPlace: "مدنية"),
  SurahModel("الْحَشْر", surahNumber: 59, ayatNumber: 24, revelationPlace: "مدنية"),
  SurahModel("الْمُمْتَحَنَة", surahNumber: 60, ayatNumber: 13, revelationPlace: "مدنية"),
  SurahModel("الصَّف", surahNumber: 61, ayatNumber: 14, revelationPlace: "مدنية"),
  SurahModel("الْجُمُعَة", surahNumber: 62, ayatNumber: 11, revelationPlace: "مدنية"),
  SurahModel("الْمُنَافِقُونَ", surahNumber: 63, ayatNumber: 11, revelationPlace: "مدنية"),
  SurahModel("التَّغَابُن", surahNumber: 64, ayatNumber: 18, revelationPlace: "مدنية"),
  SurahModel("الطَّلَاق", surahNumber: 65, ayatNumber: 12, revelationPlace: "مدنية"),
  SurahModel("التَّحْرِيم", surahNumber: 66, ayatNumber: 12, revelationPlace: "مدنية"),
  SurahModel("الْمُلْك", surahNumber: 67, ayatNumber: 30, revelationPlace: "مكية"),
  SurahModel("الْقَلَم", surahNumber: 68, ayatNumber: 52, revelationPlace: "مكية"),
  SurahModel("الْحَاقَّة", surahNumber: 69, ayatNumber: 52, revelationPlace: "مكية"),
  SurahModel("الْمَعَارِج", surahNumber: 70, ayatNumber: 44, revelationPlace: "مكية"),
  SurahModel("نُوح", surahNumber: 71, ayatNumber: 28, revelationPlace: "مكية"),
  SurahModel("الْجِن", surahNumber: 72, ayatNumber: 28, revelationPlace: "مكية"),
  SurahModel("الْمُزَّمِّل", surahNumber: 73, ayatNumber: 20, revelationPlace: "مكية"),
  SurahModel("الْمُدَّثِّر", surahNumber: 74, ayatNumber: 56, revelationPlace: "مكية"),
  SurahModel("الْقِيَامَة", surahNumber: 75, ayatNumber: 40, revelationPlace: "مكية"),
  SurahModel("الْإِنْسَان", surahNumber: 76, ayatNumber: 31, revelationPlace: "مدنية"),
  SurahModel("الْمُرْسَلَات", surahNumber: 77, ayatNumber: 50, revelationPlace: "مكية"),
  SurahModel("النَّبَأ", surahNumber: 78, ayatNumber: 40, revelationPlace: "مكية"),
  SurahModel("النَّازِعَات", surahNumber: 79, ayatNumber: 46, revelationPlace: "مكية"),
  SurahModel("عَبَسَ", surahNumber: 80, ayatNumber: 42, revelationPlace: "مكية"),
  SurahModel("التَّكْوِير", surahNumber: 81, ayatNumber: 29, revelationPlace: "مكية"),
  SurahModel("الْإِنْفِطَار", surahNumber: 82, ayatNumber: 19, revelationPlace: "مكية"),
  SurahModel("الْمُطَفِّفِين", surahNumber: 83, ayatNumber: 36, revelationPlace: "مكية"),
  SurahModel("الْإِنْشِقَاق", surahNumber: 84, ayatNumber: 25, revelationPlace: "مكية"),
  SurahModel("الْبُرُوج", surahNumber: 85, ayatNumber: 22, revelationPlace: "مكية"),
  SurahModel("الطَّارِق", surahNumber: 86, ayatNumber: 17, revelationPlace: "مكية"),
  SurahModel("الْأَعْلَى", surahNumber: 87, ayatNumber: 19, revelationPlace: "مكية"),
  SurahModel("الْغَاشِيَة", surahNumber: 88, ayatNumber: 26, revelationPlace: "مكية"),
  SurahModel("الْفَجْر", surahNumber: 89, ayatNumber: 30, revelationPlace: "مكية"),
  SurahModel("الْبَلَد", surahNumber: 90, ayatNumber: 20, revelationPlace: "مكية"),
  SurahModel("الشَّمْس", surahNumber: 91, ayatNumber: 15, revelationPlace: "مكية"),
  SurahModel("اللَّيْل", surahNumber: 92, ayatNumber: 21, revelationPlace: "مكية"),
  SurahModel("الضُّحَى", surahNumber: 93, ayatNumber: 11, revelationPlace: "مكية"),
  SurahModel("الشَّرْح", surahNumber: 94, ayatNumber: 8, revelationPlace: "مكية"),
  SurahModel("التِّين", surahNumber: 95, ayatNumber: 8, revelationPlace: "مكية"),
  SurahModel("الْعَلَق", surahNumber: 96, ayatNumber: 19, revelationPlace: "مكية"),
  SurahModel("الْقَدْر", surahNumber: 97, ayatNumber: 5, revelationPlace: "مكية"),
  SurahModel("الْبَيِّنَة", surahNumber: 98, ayatNumber: 8, revelationPlace: "مدنية"),
  SurahModel("الزَّلْزَلَة", surahNumber: 99, ayatNumber: 8, revelationPlace: "مدنية"),
  SurahModel("الْعَادِيَات", surahNumber: 100, ayatNumber: 11, revelationPlace: "مكية"),
  SurahModel("الْقَارِعَة", surahNumber: 101, ayatNumber: 11, revelationPlace: "مكية"),
  SurahModel("التَّكَاثُر", surahNumber: 102, ayatNumber: 8, revelationPlace: "مكية"),
  SurahModel("الْعَصْر", surahNumber: 103, ayatNumber: 3, revelationPlace: "مكية"),
  SurahModel("الْهُمَزَة", surahNumber: 104, ayatNumber: 9, revelationPlace: "مكية"),
  SurahModel("الْفِيل", surahNumber: 105, ayatNumber: 5, revelationPlace: "مكية"),
  SurahModel("قُرَيْش", surahNumber: 106, ayatNumber: 4, revelationPlace: "مكية"),
  SurahModel("الْمَاعُون", surahNumber: 107, ayatNumber: 7, revelationPlace: "مكية"),
  SurahModel("الْكَوْثَر", surahNumber: 108, ayatNumber: 3, revelationPlace: "مكية"),
  SurahModel("الْكَافِرُونَ", surahNumber: 109, ayatNumber: 6, revelationPlace: "مكية"),
  SurahModel("النَّصْر", surahNumber: 110, ayatNumber: 3, revelationPlace: "مدنية"),
  SurahModel("الْمَسَد", surahNumber: 111, ayatNumber: 5, revelationPlace: "مكية"),
  SurahModel("الْإِخْلَاص", surahNumber: 112, ayatNumber: 4, revelationPlace: "مكية"),
  SurahModel("الْفَلَق", surahNumber: 113, ayatNumber: 5, revelationPlace: "مكية"),
  SurahModel("النَّاس", surahNumber: 114, ayatNumber: 6, revelationPlace: "مكية"),
];