// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvWrE2DARI-Y6K8QAqxCeSx3q9IYtPDbk',
    appId: '1:523066143022:web:6b6a03715db6451322cabf',
    messagingSenderId: '523066143022',
    projectId: 'quran-app-90129',
    authDomain: 'quran-app-90129.firebaseapp.com',
    storageBucket: 'quran-app-90129.firebasestorage.app',
    measurementId: 'G-799VJJEMBR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAI3_C_RdWWJ5SYtqgT4Ymf33lseNAlPCg',
    appId: '1:523066143022:android:ed28cffcdffcf0f422cabf',
    messagingSenderId: '523066143022',
    projectId: 'quran-app-90129',
    storageBucket: 'quran-app-90129.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJPc8iY8Vy0OeSOw3nXoB2UsY6y0kIsNA',
    appId: '1:523066143022:ios:1b7c6e5b53212c6122cabf',
    messagingSenderId: '523066143022',
    projectId: 'quran-app-90129',
    storageBucket: 'quran-app-90129.firebasestorage.app',
    iosBundleId: 'com.example.quranApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJPc8iY8Vy0OeSOw3nXoB2UsY6y0kIsNA',
    appId: '1:523066143022:ios:1b7c6e5b53212c6122cabf',
    messagingSenderId: '523066143022',
    projectId: 'quran-app-90129',
    storageBucket: 'quran-app-90129.firebasestorage.app',
    iosBundleId: 'com.example.quranApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvWrE2DARI-Y6K8QAqxCeSx3q9IYtPDbk',
    appId: '1:523066143022:web:95edd86a59681d4a22cabf',
    messagingSenderId: '523066143022',
    projectId: 'quran-app-90129',
    authDomain: 'quran-app-90129.firebaseapp.com',
    storageBucket: 'quran-app-90129.firebasestorage.app',
    measurementId: 'G-NC3R192GM8',
  );

}